// ── Seed data — run once via /api/seed ──────────────────────────────────────

export const SEED_STAFF = [
  { id: 'st1', name: 'Mira Eom', role: 'Lead Stylist', color: '#B8281A' },
  { id: 'st2', name: 'Stylist 2', role: 'Stylist', color: '#8B5E3C' },
]

export const SEED_SERVICES = [
  { id: 's1', name: 'Cut & Style', duration: 60, price: 95, color: '#3D7A5C' },
  { id: 's2', name: 'Balayage', duration: 180, price: 280, color: '#B8281A' },
  { id: 's3', name: 'Full Color', duration: 120, price: 160, color: '#8B5E3C' },
  { id: 's4', name: 'Toner', duration: 45, price: 65, color: '#D4B896' },
  { id: 's5', name: 'Japanese Straight', duration: 240, price: 380, color: '#5C4A3A' },
  { id: 's6', name: 'Blow Dry', duration: 45, price: 65, color: '#7A5C2E' },
  { id: 's7', name: 'Gloss Treatment', duration: 60, price: 85, color: '#2E7D9E' },
  { id: 's8', name: 'Trim', duration: 30, price: 55, color: '#6E6E3A' },
  { id: 's9', name: 'Korean Style Wedding Hair', duration: 120, price: 220, color: '#9E4D7A' },
]

export const SEED_DAYS_OFF = [
  { id: 'do1', stylist_id: 'st1', type: 'recurring', weekday: 1, note: 'Regular day off' },
  { id: 'do2', stylist_id: 'st1', type: 'recurring', weekday: 3, note: 'Regular day off' },
  { id: 'do3', stylist_id: 'st1', type: 'recurring', weekday: 4, note: 'Regular day off' },
  { id: 'do4', stylist_id: 'st2', type: 'recurring', weekday: 1, note: 'Day off' },
  { id: 'do5', stylist_id: 'st2', type: 'recurring', weekday: 2, note: 'Day off' },
  { id: 'do6', stylist_id: 'st2', type: 'recurring', weekday: 3, note: 'Day off' },
  { id: 'do7', stylist_id: 'st2', type: 'recurring', weekday: 4, note: 'Day off' },
  { id: 'do8', stylist_id: 'st2', type: 'recurring', weekday: 5, note: 'Day off' },
]

export const SEED_CLIENTS = [
  { id: 'c1', name: 'Sophie Nakamura', phone: '0412 384 721', email: 'sophie@email.com', tag: 'regular', notes: 'Balayage client. Wella 8/0 + 9/16 mix. Warm tones. Sensitive scalp — no bleach on roots. Visits every 10-12 weeks.', last_visit: '2025-03-28', total_spend: 1840 },
  { id: 'c2', name: 'Ariana Kowalski', phone: '0435 917 263', email: '', tag: 'regular', notes: 'Japanese straightening every 6 months. Fine hair. Always adds blowout. Wants volume at root.', last_visit: '2025-04-02', total_spend: 2200 },
  { id: 'c3', name: 'Megan Tran', phone: '0401 562 849', email: 'megan.t@email.com', tag: 'new', notes: 'First visit. Wants ash blonde from level 6 brown. 2-step process needed. Patch test done ✓', last_visit: '', total_spend: 0 },
  { id: 'c4', name: 'Rachel Kim', phone: '0478 130 594', email: '', tag: 'regular', notes: 'Short bob. Trim every 5-6 weeks. Stacked back. No color.', last_visit: '2025-04-10', total_spend: 960 },
  { id: 'c5', name: 'Jenna Park', phone: '0423 651 807', email: 'jenna.p@gmail.com', tag: 'regular', notes: 'Medium length layers. Warm brunette. Cut every 8 weeks. No bleach.', last_visit: '2025-07-20', total_spend: 640 },
  { id: 'c6', name: 'Lisa Chen', phone: '0447 293 510', email: '', tag: 'regular', notes: 'Highlights + toner. Very fine hair, gentle handling. No heat over 180°C.', last_visit: '2025-07-15', total_spend: 890 },
  { id: 'c7', name: 'Amy Wilson', phone: '0461 748 932', email: 'amy.w@outlook.com', tag: 'new', notes: 'Referred by Sophie. First balayage. Dark base level 4. Nervous about lightening.', last_visit: '', total_spend: 0 },
  { id: 'c8', name: 'Yuna Lee', phone: '0412 039 476', email: '', tag: 'regular', notes: 'Korean style blowout every 2-3 weeks. Prefers volume at crown. Thick straight hair.', last_visit: '2025-07-25', total_spend: 520 },
  { id: 'c9', name: 'Grace Kim', phone: '0438 801 254', email: 'grace.kim@email.com', tag: 'regular', notes: 'Root touch-up every 6 weeks. Level 7 ash blonde. Sensitive to ammonia — use low-lift colour.', last_visit: '2025-07-18', total_spend: 1100 },
  { id: 'c10', name: 'Tina Nguyen', phone: '0455 362 719', email: '', tag: 'new', notes: 'Walk-in. Trim + blow dry. Thick wavy hair. Interested in future colour service.', last_visit: '', total_spend: 0 },
  { id: 'c11', name: 'Sarah Oh', phone: '0419 574 083', email: 'sarah.oh@gmail.com', tag: 'regular', notes: 'Loyal client 2+ years. Full colour L6 warm brown every 8 weeks. Always adds gloss treatment.', last_visit: '2025-07-22', total_spend: 1760 },
  { id: 'c12', name: 'Mia Tanaka', phone: '0492 817 340', email: '', tag: 'new', notes: 'Wedding hair trial — Korean bridal updo. Date: Nov 2025. Wants practice run first.', last_visit: '', total_spend: 0 },
  { id: 'c13', name: 'Chloe Park', phone: '0431 650 928', email: 'chloe.p@icloud.com', tag: 'regular', notes: 'Balayage maintenance every 4 months. Level 8 base. Loves icy toner. Very particular about tone.', last_visit: '2025-06-30', total_spend: 1320 },
  { id: 'c14', name: 'Hana Seo', phone: '0467 193 582', email: '', tag: 'new', notes: 'Black to soft brown. Will need multiple sessions. Level 2 base. Patch test booked.', last_visit: '', total_spend: 0 },
  { id: 'c15', name: 'Emily Park', phone: '0411 728 503', email: 'emily.park@gmail.com', tag: 'regular', notes: 'Root colour + toner every 7 weeks. Level 6 cool blonde. Scalp is dry — use moisture mask.', last_visit: '2025-08-01', total_spend: 1450 },
  { id: 'c16', name: 'Jessica Moon', phone: '0443 291 867', email: '', tag: 'regular', notes: 'Balayage + trim twice a year. Long thick hair. Takes full 4hrs. Prefers warm caramel tones.', last_visit: '2025-05-14', total_spend: 2100 },
  { id: 'c17', name: 'Naomi Choi', phone: '0457 836 142', email: 'naomi.c@hotmail.com', tag: 'regular', notes: 'Gloss treatment every 6 weeks. Colour-treated hair. Level 7 brunette. Very low maintenance.', last_visit: '2025-07-30', total_spend: 780 },
  { id: 'c18', name: 'Kate Yamamoto', phone: '0429 054 371', email: '', tag: 'new', notes: 'Referral from Grace Kim. Wants balayage for the first time. Medium length, natural level 5.', last_visit: '', total_spend: 0 },
  { id: 'c19', name: 'Dana Lim', phone: '0416 947 280', email: 'dana.lim@gmail.com', tag: 'regular', notes: 'Full colour L5 dark brown every 8-9 weeks. Sensitive roots. Doesn\'t like foils near face.', last_visit: '2025-07-10', total_spend: 1200 },
  { id: 'c20', name: 'Vivian Kang', phone: '0482 315 796', email: '', tag: 'regular', notes: 'Cut & style every 6 weeks. Shoulder length bob. Loves blowout finish. No colour.', last_visit: '2025-08-05', total_spend: 720 },
  { id: 'c21', name: 'Angela Shin', phone: '0431 087 524', email: 'angela.s@icloud.com', tag: 'regular', notes: 'Colour correction client. Came in brassy, now maintained at level 8 cool blonde. Toner every 8 weeks.', last_visit: '2025-07-28', total_spend: 1650 },
  { id: 'c22', name: 'Michelle Hwang', phone: '0448 761 039', email: '', tag: 'new', notes: 'New client. Wants Korean-style soft perm look via blowout. Very fine hair, length to shoulders.', last_visit: '', total_spend: 0 },
  { id: 'c23', name: 'Priya Sharma', phone: '0463 520 814', email: 'priya.s@email.com', tag: 'regular', notes: 'Trim every 8 weeks. Long thick Indian hair. No colour ever. Loves blowout. Tip 15-20% always.', last_visit: '2025-07-15', total_spend: 430 },
  { id: 'c24', name: 'Zoe Anderson', phone: '0411 394 725', email: '', tag: 'regular', notes: 'Balayage + toner client. Level 6 to 9 lift. Every 4 months. Has had reactions to some developers — patch test always.', last_visit: '2025-04-20', total_spend: 2400 },
  { id: 'c25', name: 'Becky Nguyen', phone: '0492 038 561', email: 'becky.n@gmail.com', tag: 'new', notes: 'First visit. Short pixie cut maintenance. No colour currently but open to toner.', last_visit: '', total_spend: 0 },
  { id: 'c26', name: 'Lily Matsuda', phone: '0427 613 840', email: '', tag: 'regular', notes: 'Japanese straight perm every 8 months. Very long hair. Full day service. Books months ahead.', last_visit: '2025-03-10', total_spend: 2600 },
  { id: 'c27', name: 'Irene Bae', phone: '0453 871 296', email: 'irene.bae@outlook.com', tag: 'regular', notes: 'Root colour every 6 weeks. Level 6 warm brown. Always brings reference photos. Talkative — allow extra time.', last_visit: '2025-08-02', total_spend: 1380 },
  { id: 'c28', name: 'Tiffany Jo', phone: '0418 247 953', email: '', tag: 'new', notes: 'New. Came for wedding hair quote. Korean bridal style. Wedding in March 2026.', last_visit: '', total_spend: 0 },
  { id: 'c29', name: 'Christine Lee', phone: '0445 093 627', email: '', tag: 'regular', notes: 'Balayage L5-8 every 5 months. Fine hair — max 20vol developer. Add toner always.', last_visit: '2025-06-12', total_spend: 1900 },
  { id: 'c30', name: 'Anna Petrova', phone: '0461 738 402', email: 'anna.p@gmail.com', tag: 'regular', notes: 'Full colour — cool dark brown L5. Hates orange tones. Every 8 weeks. Very precise about results.', last_visit: '2025-07-25', total_spend: 1250 },
  { id: 'c31', name: 'Suji Han', phone: '0432 801 574', email: '', tag: 'regular', notes: 'Trim + blowout every 5 weeks. Very straight fine Korean hair. No colour.', last_visit: '2025-08-07', total_spend: 480 },
  { id: 'c32', name: 'Mei Lin', phone: '0419 650 283', email: 'mei.lin@hotmail.com', tag: 'new', notes: 'New client. Interested in full colour (dark to medium brown). Level 3 base. Fine hair.', last_visit: '', total_spend: 0 },
  { id: 'c33', name: 'Nadia Volkov', phone: '0476 324 918', email: '', tag: 'regular', notes: 'Highlights every 10 weeks. Level 7 warm blonde. Very thick hair — add extra toner time.', last_visit: '2025-07-08', total_spend: 1560 },
  { id: 'c34', name: 'Soo-Yeon Cho', phone: '0441 587 362', email: 'sooyeon@email.com', tag: 'regular', notes: 'Gloss + blowout combo every 5 weeks. Level 6 warm brunette. Very loyal. Always tips well.', last_visit: '2025-08-03', total_spend: 920 },
  { id: 'c35', name: 'Rina Inoue', phone: '0428 093 741', email: '', tag: 'new', notes: 'First time colour client. Wants balayage. Long hair level 5. Seen lots of inspo on Instagram.', last_visit: '', total_spend: 0 },
  { id: 'c36', name: 'Elaine Wu', phone: '0453 716 824', email: 'elaine.wu@gmail.com', tag: 'regular', notes: 'Root touch-up L6 every 7 weeks. Medium length. Always wants trim after colour. Sensitive scalp.', last_visit: '2025-07-20', total_spend: 1100 },
  { id: 'c37', name: 'Sandra Kim', phone: '0469 230 587', email: '', tag: 'regular', notes: 'Cut & style every 5 weeks. Short layers. No colour. Very specific about shape — show before cutting.', last_visit: '2025-08-04', total_spend: 560 },
  { id: 'c38', name: 'Hyun-Jee Oh', phone: '0414 865 302', email: 'hyunjee.oh@icloud.com', tag: 'regular', notes: 'Full colour warm L6 every 8 weeks + gloss. Colour-treated for 3 years. Hair in good condition.', last_visit: '2025-07-14', total_spend: 1480 },
  { id: 'c39', name: 'Penny Liu', phone: '0437 192 046', email: '', tag: 'new', notes: 'Walk-in enquiry. Wants balayage + cut. Long hair, natural level 7 light brown. Budget conscious.', last_visit: '', total_spend: 0 },
  { id: 'c40', name: 'Jasmine Park', phone: '0462 847 503', email: 'jasmine.p@email.com', tag: 'regular', notes: 'Balayage twice yearly. Level 8 golden blonde. Fine hair — be careful with tension. Adds toner + blowout.', last_visit: '2025-05-30', total_spend: 2200 },
  { id: 'c41', name: 'Helen Chung', phone: '0421 374 690', email: '', tag: 'regular', notes: 'Japanese straight every 7 months. Shoulder length. Hair is in great shape. Quick to process.', last_visit: '2025-02-18', total_spend: 1600 },
  { id: 'c42', name: 'Rosa Martinez', phone: '0448 029 713', email: 'rosa.m@gmail.com', tag: 'new', notes: 'Very long dark hair. Wants soft ombre/balayage effect. Level 2 base — will need multiple sessions.', last_visit: '', total_spend: 0 },
  { id: 'c43', name: 'Ji-Eun Park', phone: '0473 581 924', email: '', tag: 'regular', notes: 'Root colour L5 + toner every 7 weeks. Medium bob. Very detail-oriented — always check shade before applying.', last_visit: '2025-07-30', total_spend: 1300 },
  { id: 'c44', name: 'Nicole Tan', phone: '0415 736 281', email: 'nicole.tan@outlook.com', tag: 'regular', notes: 'Trim + blowout every 4 weeks. Shoulder-length. No colour. Comes in very regularly. Always on time.', last_visit: '2025-08-06', total_spend: 640 },
  { id: 'c45', name: 'Lucy Kwon', phone: '0456 293 817', email: '', tag: 'new', notes: 'Referral. Wants to fix previous bad balayage — patchy and brassy. Level 7 with visible banding.', last_visit: '', total_spend: 0 },
  { id: 'c46', name: 'Fiona Zhao', phone: '0431 847 260', email: 'fiona.z@gmail.com', tag: 'regular', notes: 'Colour + trim every 8 weeks. Cool ash brown L6. Reacts to certain brands — use Wella only.', last_visit: '2025-07-22', total_spend: 1200 },
  { id: 'c47', name: 'Sera Lim', phone: '0468 013 594', email: '', tag: 'regular', notes: 'Full balayage + toner every 5 months. Very long hair L8 blonde. Takes 4-5 hours total.', last_visit: '2025-04-15', total_spend: 2800 },
  { id: 'c48', name: 'Kat Fujimoto', phone: '0422 619 483', email: 'kat.f@icloud.com', tag: 'new', notes: 'First visit. Short bob. Wants clean cut and toner to remove brassiness. Level 7 currently.', last_visit: '', total_spend: 0 },
  { id: 'c49', name: 'Mina Yoon', phone: '0491 374 806', email: '', tag: 'regular', notes: 'Trim + blowout every 3-4 weeks. Thick long hair. No colour. Loves dry styling finish.', last_visit: '2025-08-08', total_spend: 380 },
  { id: 'c50', name: 'Diana Kwon', phone: '0437 852 019', email: 'diana.k@email.com', tag: 'regular', notes: 'Root colour L5 warm brown every 6 weeks. Short bob. Very punctual. Hates waiting.', last_visit: '2025-08-01', total_spend: 1050 },
  { id: 'c51', name: 'Olivia Ng', phone: '0414 267 930', email: '', tag: 'new', notes: 'New client via Instagram. Wants lived-in blonde balayage. Natural dark level 4. Long hair.', last_visit: '', total_spend: 0 },
  { id: 'c52', name: 'Claire Ahn', phone: '0453 091 748', email: 'claire.ahn@gmail.com', tag: 'regular', notes: 'Colour correction ongoing — was over-bleached. Now maintaining at level 8 with regular toners.', last_visit: '2025-07-10', total_spend: 1900 },
  { id: 'c53', name: 'Rebecca Choi', phone: '0426 584 137', email: '', tag: 'regular', notes: 'Cut & blowout every 5 weeks. Medium length. No colour. Loves volume and movement.', last_visit: '2025-08-03', total_spend: 490 },
  { id: 'c54', name: 'Stella Yoo', phone: '0471 308 625', email: 'stella.y@hotmail.com', tag: 'regular', notes: 'Balayage maintenance every 4 months + toner. Level 8 warm blonde. Fine hair — low volume developer.', last_visit: '2025-06-05', total_spend: 2050 },
  { id: 'c55', name: 'Alice Kang', phone: '0444 726 381', email: '', tag: 'new', notes: 'Enquiry for Korean wedding hair. Wants trial before event. Event in April 2026.', last_visit: '', total_spend: 0 },
  { id: 'c56', name: 'Bomi Jeon', phone: '0418 593 270', email: 'bomi.j@gmail.com', tag: 'regular', notes: 'Full colour L6 every 8 weeks. Warm chestnut tone. Scalp is very sensitive — do strand test first.', last_visit: '2025-07-28', total_spend: 1150 },
  { id: 'c57', name: 'Sunni Park', phone: '0463 817 402', email: '', tag: 'regular', notes: 'Gloss treatment every 6 weeks. Maintains warm tone. Easy client. Very happy with results.', last_visit: '2025-08-02', total_spend: 620 },
  { id: 'c58', name: 'Lauren Kim', phone: '0429 145 873', email: 'lauren.k@icloud.com', tag: 'new', notes: 'Moving from Melbourne. Looking for regular hair stylist. Currently balayage level 8 warm.', last_visit: '', total_spend: 0 },
  { id: 'c59', name: 'Hee-Young Cho', phone: '0491 036 584', email: '', tag: 'regular', notes: 'Root + toner every 7 weeks. Medium length. Cool ash L7. Always wants blowout after colour.', last_visit: '2025-07-25', total_spend: 1300 },
  { id: 'c60', name: 'Tamara Nguyen', phone: '0436 802 517', email: 'tamara.n@email.com', tag: 'regular', notes: 'Trim every 6 weeks. Long layers. No colour. Very easy client. Loves head massage during shampoo.', last_visit: '2025-08-04', total_spend: 310 },
  { id: 'c61', name: 'Ji-Young Lee', phone: '0412 947 368', email: '', tag: 'new', notes: 'Korean student. Wants blowout + trim. First time at salon. Budget limited.', last_visit: '', total_spend: 0 },
  { id: 'c62', name: 'Alicia Pham', phone: '0457 230 891', email: 'alicia.p@gmail.com', tag: 'regular', notes: 'Full colour warm brown L5 every 8 weeks. Medium thick hair. Always adds gloss. Great tipper.', last_visit: '2025-07-18', total_spend: 1400 },
  { id: 'c63', name: 'Nora Kim', phone: '0443 618 027', email: '', tag: 'regular', notes: 'Balayage twice a year. Level 6-9 lift. Very long thick hair — budget 4.5 hrs.', last_visit: '2025-03-22', total_spend: 2700 },
  { id: 'c64', name: 'Wren Takahashi', phone: '0426 073 819', email: 'wren.t@outlook.com', tag: 'new', notes: 'New client. Wants big chop — currently very long, wants short bob. Nervous. Book extra consultation time.', last_visit: '', total_spend: 0 },
  { id: 'c65', name: 'Hyo-Jung Shin', phone: '0468 395 102', email: '', tag: 'regular', notes: 'Colour L5 warm + trim every 7-8 weeks. Curly-ish ends. Doesn\'t want it straightened.', last_visit: '2025-07-30', total_spend: 1050 },
  { id: 'c66', name: 'May Chen', phone: '0492 147 836', email: 'may.chen@gmail.com', tag: 'regular', notes: 'Root touch-up L6 + toner every 6 weeks. Ash blonde. Allergic to PPD — use PPD-free dye only.', last_visit: '2025-08-05', total_spend: 1300 },
  { id: 'c67', name: 'Ingrid Sato', phone: '0411 659 274', email: '', tag: 'new', notes: 'Japanese background, long black hair. Wants subtle balayage. Very hesitant — ease her in slowly.', last_visit: '', total_spend: 0 },
  { id: 'c68', name: 'Yoojin Han', phone: '0445 382 097', email: 'yoojin.h@icloud.com', tag: 'regular', notes: 'Blowout every 2 weeks. Occasionally adds toner. Very thick straight hair. Tip always $20+.', last_visit: '2025-08-07', total_spend: 740 },
  { id: 'c69', name: 'Tara Singh', phone: '0461 074 538', email: '', tag: 'new', notes: 'Indian hair, very thick and dark. Interested in highlights for first time. Manage expectations.', last_visit: '', total_spend: 0 },
  { id: 'c70', name: 'Erica Moon', phone: '0434 918 673', email: 'erica.m@gmail.com', tag: 'regular', notes: 'Full balayage + toner + trim every 4-5 months. Level 7 warm golden. Long fine hair. Very trusting client.', last_visit: '2025-06-18', total_spend: 2350 },
]
